### ISSUE TITLE
Compilation error: source and target versions

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/pdf-enrichment#1]
On my machine running `mvn package` fails with:

```
[INFO] Compiling 1 source file to /home/a3nm/apps/pdf-enrichment/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.929 s
[INFO] Finished at: 2019-04-03T22:33:35+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pdfenrichment: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

From what I can see on the Internet [here](https://github.com/jflex-de/jflex/issues/400) and [here](https://maven.apache.org/plugins/maven-compiler-plugin/index.html) this could be avoided by following the recommended practice of indicating explicitly the desired source and target.

Does this make sense? (Sorry I don't know anything about maven, so maybe it doesn't.)

**Comment by PierreSenellart** [comment]
Fixed in e5cfc0a. I also don't know much about maven, so I hope this is enough. Please let me know if this works for you.

**Comment by cphillips3** [comment]
I'm getting the same error. Not sure WHERE exactly I'm supposed to change these source and target options. Where is the pom file located? I can't find it anywhere in my maven directory.

I'm doing:
mvn compile -source 1.6 -target 1.6 -U

And it still reports the same error.

**Comment by a3nm** [comment]
Sorry Pierre that I had not reacted earlier. @cphillips3 doing `git pull` and `mvn package` now works for me, have you tried this?

**Comment by PierreSenellart** [comment]
The `pom.xml` file is at the root of the `pdf-enrichment` project. I have just tried a `git pull` and `mvn package` on a clean machine (with an empty Maven repository in particular), this seems to work fine.
